name = "visit-log"
main = "src/index.js"
compatibility_date = "2026-08-01"
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["0 5 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "visit-log-db"
database_id = "59731293-bfb9-4f69-80a4-b320e333db0e"
preview_database_id = "f96083e4-452c-4745-a7b9-23ebf00186b3"

[[routes]]
pattern = "csfields.com/*"
zone_name = "csfields.com"

[[routes]]
pattern = "www.csfields.com/*"
zone_name = "csfields.com"
